### ISSUE TITLE
loading 1.0 

### ISSUE THREAD

**Issue by Slabhub** [mlhiter/logseq-task-done-time-mini#1]
Error caught by UI!
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmeta%2C%20obj%2C%20%24prop__GT_key%24%2C%20%24key__GT_prop%24%2C%20%24recursive_QMARK_%24%2C%20%24__arr%24%2C%20%24__cnt%24%2C%20%24__hash%24%2C%20%24cljs%24lang%24protocol_mask%24partition0%24%24%2C%20%24cljs%24lang%24protocol_mask%24partition1%24%24%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Slabhub** [comment]
os : mac os sonoma

**Comment by mlhiter** [comment]
OK, I will fix this bug today. @Slabhub

**Comment by mlhiter** [comment]
@Slabhub fixed it. 
And some other things: 
	If you cannot use logseq because of this issues.
	You can delete plugin in `~\.logseq\preferences.json`
``` json
"externals": [
    ".\\logseq-task-done-time-mini"
  ]
```
just delete this array item and ctrl+R refresh your logseq.
