### ISSUE TITLE
插件完全不生效

### ISSUE THREAD

**Issue by Andante99** [mlhiter/logseq-task-done-time-mini#4]
如题，Mac OS系统，使用本插件完全不生效，插件设置中的几种模式都是如此；关闭其它插件也没有生效（哭哭😭一直有记录DONE时间的需求，看到插件演示很心动的说。。。）

**Comment by mlhiter** [comment]
这样嘛，我正好换了 mac 电脑，但是我最近没怎么用自己的这个插件😂

**Comment by mlhiter** [comment]
@Andante99 刚测试了一下，好使捏

**Comment by Andante99** [comment]
后续：把logseq更新到0.10.9，插件就可以顺畅使用了😂 看来是之前版本太旧了hhh

**Comment by mlhiter** [comment]
@Andante99 哈哈能用就行，还有什么其他的需求和问题提新的 issue 哈，我一般会尽快更新。顺便求个免费的 star🥹
