### ISSUE TITLE
时间标记重复生成

### ISSUE THREAD

**Issue by ANNOARK** [mlhiter/logseq-task-done-time-mini#5]
点击完成或ctrl+enter完成时，会重复添加时间
![recording](https://github.com/user-attachments/assets/60c01bb6-aae6-4bee-9ffc-7de5cbd94cc2)

**Comment by ANNOARK** [comment]
使用property模式则无法创建property，难道是日期格式的问题？

**Comment by mlhiter** [comment]
@ANNOARK 属性模式得符合属性的书写方法，正确示范例如：
date:: [[{date}]]

**Comment by mlhiter** [comment]
> 点击完成或ctrl+enter完成时，会重复添加时间 ![recording](https://private-user-images.githubusercontent.com/43340211/370148675-60c01bb6-aae6-4bee-9ffc-7de5cbd94cc2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTM1NDksIm5iZiI6MTcyNzI1MzI0OSwicGF0aCI6Ii80MzM0MDIxMS8zNzAxNDg2NzUtNjBjMDFiYjYtYWFlNi00YmVlLTlmZmMtN2RlNWNiZDk0Y2MyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjVhMGE0NTE1NTNiNmY1ZjgyZmI5MjM3ZjU0OTI5OTUwZjViYzQwYTdhNzkwOWM2ZjYwZDU3NmY0NGZlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbRiZQG066IC4EShHbhGL6k2s-cTCJx2kwNUTgK6htQ) [ ![recording](https://private-user-images.githubusercontent.com/43340211/370148675-60c01bb6-aae6-4bee-9ffc-7de5cbd94cc2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTM1NDksIm5iZiI6MTcyNzI1MzI0OSwicGF0aCI6Ii80MzM0MDIxMS8zNzAxNDg2NzUtNjBjMDFiYjYtYWFlNi00YmVlLTlmZmMtN2RlNWNiZDk0Y2MyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjVhMGE0NTE1NTNiNmY1ZjgyZmI5MjM3ZjU0OTI5OTUwZjViYzQwYTdhNzkwOWM2ZjYwZDU3NmY0NGZlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbRiZQG066IC4EShHbhGL6k2s-cTCJx2kwNUTgK6htQ) ](https://private-user-images.githubusercontent.com/43340211/370148675-60c01bb6-aae6-4bee-9ffc-7de5cbd94cc2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTM1NDksIm5iZiI6MTcyNzI1MzI0OSwicGF0aCI6Ii80MzM0MDIxMS8zNzAxNDg2NzUtNjBjMDFiYjYtYWFlNi00YmVlLTlmZmMtN2RlNWNiZDk0Y2MyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjVhMGE0NTE1NTNiNmY1ZjgyZmI5MjM3ZjU0OTI5OTUwZjViYzQwYTdhNzkwOWM2ZjYwZDU3NmY0NGZlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbRiZQG066IC4EShHbhGL6k2s-cTCJx2kwNUTgK6htQ) [ ](https://private-user-images.githubusercontent.com/43340211/370148675-60c01bb6-aae6-4bee-9ffc-7de5cbd94cc2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTM1NDksIm5iZiI6MTcyNzI1MzI0OSwicGF0aCI6Ii80MzM0MDIxMS8zNzAxNDg2NzUtNjBjMDFiYjYtYWFlNi00YmVlLTlmZmMtN2RlNWNiZDk0Y2MyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjVhMGE0NTE1NTNiNmY1ZjgyZmI5MjM3ZjU0OTI5OTUwZjViYzQwYTdhNzkwOWM2ZjYwZDU3NmY0NGZlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbRiZQG066IC4EShHbhGL6k2s-cTCJx2kwNUTgK6htQ)

修复了，正好漏了你那种日期格式
