### ISSUE TITLE
在当天日志里新建的任务依然会添加完成信息

### ISSUE THREAD

**Issue by ANNOARK** [mlhiter/logseq-task-done-time-mini#6]
已在设置中设置（未勾选该选项）
![image](https://github.com/user-attachments/assets/e823ccac-6c97-41ca-b39a-306bcb3fcd1a)
在当天日志中新建任务，完成时依然会添加完成信息
![recording](https://github.com/user-attachments/assets/8f1eecbd-9ce4-4d39-8816-fa8ff0dbd334)

**Comment by mlhiter** [comment]
真是，我看一下哈🤔

**Comment by mlhiter** [comment]
@ANNOARK 已修复，你更新一下就好了，有什么其他问题和建议可以开新的 issue🥹
