### ISSUE TITLE
content模式 完成时间总是在下面，重装了几次不生效

### ISSUE THREAD

**Issue by liyongjian5179** [mlhiter/logseq-task-done-time-mini#7]
![image](https://github.com/user-attachments/assets/8c379815-e6e5-45e1-bc1c-8332baf6d005)

![image](https://github.com/user-attachments/assets/0d8e2a4c-1c7f-4a9e-af18-ce44670a2d18)

**Comment by mlhiter** [comment]
![CleanShot 2024-12-12 at 20 34 07@2x](https://github.com/user-attachments/assets/748b9491-b266-4571-84f2-cedf54e14333)
这个的原因？
@liyongjian5179

**Comment by mlhiter** [comment]
再不然的话就是你的主题之类的影响的

**Comment by liyongjian5179** [comment]
关了也不好使，可能我得把所有的插件都卸载了 再观察下了

**Comment by mlhiter** [comment]
其实很简单，就是你有个主题或者插件可能影响了这个的布局。你可以尝试找到是哪个主题的锅关掉它，或者自己写 css 调整一下

**Comment by liyongjian5179** [comment]
enen  好哒
